absolute_project_folder_path: "C:\\Users\\novak\\Downloads\\Python SQL Project"

pos_copper: "Position_Copper.csv"
pos_prop: "Position_Prop.csv"
pos_zinclead: "Position_ZincLead.csv"

hist_price: "Historical Price.csv"